### ISSUE TITLE
Ban rate? 

### ISSUE THREAD

**Issue by yiyska** [dhkatz/t5de#1]
Okay, so I have no issue what so ever, but I don't want my main to get banned
so I'm asking if there's a way to avoid getting banned and be 100% safe with my main account (like using imvulite) 

also asking how long it'll take to get banned if I abuse everything XD

Thanks.

**Comment by dhkatz** [comment]
I can't really tell you to be honest. This was more of just a way to show others how T5DE clients are created. It does work (I might have to update the client version) but I have no idea what triggers a ban.

It seems to be if you're using *use commands too much it can, but otherwise I don't know. I've already blocked most of the telemetry in this client

**Comment by EFEVE** [comment]
I asked this same question to a friend of mine who's been using t4 and t5 clients (including this one) since before the pandemic started, with the same account. According to them, the things that are most certain to trigger a ban are:

- Using black market poses in public rooms.

- Saving outfits **that include items you haven't bought**.

- Wearing AP items **without having bought the AP badge**.

**Comment by dhkatz** [comment]
See the second point doesn't make sense to me. You can save outfits you don't own on the regular client, and I do it all the time when I want to save something to work on/buy later.

I think it's more so related to putting on a ton of stuff you don't own (similar to what I was saying about *use codes).

For some reason they don't seem to care as much about furniture

**Comment by dhkatz** [comment]
It is technically easy to edit but not in any user friendly way. If you wanted to add more changes it requires you right now to know the contents of basically every file within the IMVU client. See my comment in #2 for what I think a better future is.

**Comment by VensGTH** [comment]
Also make sure to not derive products or use the creator tool at all if you're not VIP and/or a creator
