### ISSUE TITLE
Shameless Suggestions

### ISSUE THREAD

**Issue by yiyska** [dhkatz/t5de#2]
As I mentioned in the other " #1 issue", I'm giving a shameless suggestions here. 

> 1 | **Ability to turn on/off T5dE settings**
- Have a tab in settings that allows for you to enable/disable t5de settings with better choices and notes.

Example:

**Settings**  |        IMVU version ###.#
_T5DE_  |    **Safe**
     [  ]   Enable camera everywhere. 
          (`*hiresnobg` / `*hiresnob`)
     [  ]   Remove advertisements. 
          (Doesn't include home ads, since it includes deals that some people may want.)
     [  ]   Remove IMVU tracking. 
          (Includes room tracking, if you want to show your room location in pics, enable this.)
     [  ]   Add mute/boot button. 
          (Allows for you to mute/boot people from **your** screen.)
     |    **Risky**
     [  ]    Show AP products. 
          (The risk of getting banned is lower if u disallow AP products.)
     [  ]    Allow AP products. 
          (Unable to wear AP products even with *use and unable to see AP rooms.)
     [  ]    Allow `*use` anywhere. 
          (Only other users with modified clients will see clothes worn this way.
          Furniture can be seen by mobile users as well.)
     [  ]    Allow new room filters.
          (Able to change occupancy filter to 'Non-Empty' and '1 Person'.
          It's risky, but it shouldn't be *that* risky.)

> 2 | **Camera everywhere** *
- Ability to actually press on the camera, not having to use `*hiresnobg` and `*hiresnob`.

> 3 | **Location in pics** *
- Similar to "**Remove IMVU Tracking**", but for this one it's like the remove furniture button, in which you allow room location tracking for 1 pic only. 

> 4 | **Safe and Unsafe client**
- If it's impossible to add settings due to the fact that the modifications have to be applied while installing, make an **unsafe** and **safe** versions. 
It should be easy if you know which is bannable and which isn't, you can ask DataMine in IMVU Mafias discord server about it since he's the creator of the original T4DE. (as far as I know.)

> 5 | **Fake stuff**
- This is just for fun, but it's to fake the amount of credits you have, fake room visitor count, fake room occupants, fake room name, just basically being able to fake everything that "changes".

> 6 | **More info**
- Have more info on things and people, such as their profile having their user ID, the room having the room link and u can copy it, when you press on 'more info' on products it shows the derivation tree, user creator level as a badge, etc.

> 7 | **Right clicks**
- Ability to right click on things like how BetterDiscord does it, on room pics, profile pics, badges, etc.

> 8 | **Easier mute** *
- In exchange of having to press on profile, block and then mute, u can just press on the avatar and press on mute just like block and boot.

> 9 | **Anti-spam** *
- When someone join the room, they're automatically muted till they say something that isn't a spam of any type, or unless they're not Guest_ users + older than # days old in the game. 
(but for non guest users, it'll only show that they joined, without loading their products or anything else till they talk.)
Not only will it stop you from loading useless people in rooms, it'll also stop you from getting spammed / crashed.

> 10 | **Mute** *
- Have more mute choices, 
1. Mute room:
 (Stops IMVU from flashing if there's any notification from that room.)
2. Muting a user won't make IMVU/room flash even when they leave the room, in exchange of that it will either just show "### Has left chat" or nothing at all.
3. Muting action:
 (Not actions on yourself, actions that others use such as dancing actions and such. In case a new crash product come into light, it'll stop you from crashing also stop making you see something you may have wished to see.)
4. Mute music: 
 (Unlike in the settings, this one just doesn't load music products at all. It'll be helpful if you see a user who has 40,00kbs+ due to music products, since if you just don't load their music product, their kbs will be a lot lower.)

Last one, this one is for you tho:

> 11 | **Paid features**
- If it's possible to put T5DE settings, make it for subscribed and specific people only. 
If not, then make a safe client, make it for paid users and unsafe version for everyone. 

_this took me a while to finish, sorry that it's so long_

**PS**: The features that I added `*` next to are the ones that I mostly want/need, I really will be thankful if u help even if just showing me _da wae_ of how to add them.

**Comment by dhkatz** [comment]
I've actually been meaning to rewrite a lot of this stuff at some point. This should all be technically possible. However, I'd like to write a new way of patching the client so that's it's way easier to do most of this stuff. Probably like a plugin system.

I guess to treat it like how BetterDiscord is to Discord with their plugin system. I'm not exactly sure how this would look, but if you have any ideas or know anyone that would be interested in expanding this like you suggest, I'd be open for discussion.

 In theory, it is also possible to modify the new client as well, as I've already experimented with a bit.

**Comment by dhkatz** [comment]
Going to be writing this here for myself and for comments. This is some initial thoughts about a plugin system.

The plugin system would have to be split up into two parts. A JavaScript side and a Python side. I wish it could all be one language but it's unfortunately not possible.

Instead of plugins applying a bunch of manual patching like I currently have, I stead patch in a plugin system into the client itself.

For example, the client knows when you get an invite, why not hook into that and let plugins react to an invite being received?

Maybe you want to add something to the menu when you click on avatars, well we can hook into that too and let plugins add onto the existing menus easily!

For example it might look something like this:

```javascript

class MutePlugin extends Plugin {
  constructor() {
    this.events.on('render:avatarmenu', this.render.bind(this))
  }

  render(menu) {
    menu.buttons.push({
      name: 'Mute'
    }) // Some button information
  }
}
```

This is a **very basic** example and the actual implementation would be different but I think it would be really cool.

**Comment by dhkatz** [comment]
I was thinking about a Discord server too. Would probably help get people in on this sort of project faster. Give me a bit to make one

**Comment by dhkatz** [comment]
The Discord is available here now https://discord.gg/5zkJuKZVTK

I also added to the README, very basic right now but it works
